### PR TITLE
Update Stripe.php

### PR DESCRIPTION
**Pull request by tenkraD**
Mount JS Stripe Elements to a div

### CODE REVIEW

**Comment by aimeos** [comment]
We've changed the type to "container" now in ai-client-html so it's independent of the actually used tag. Furthermore, you shouldn't change dash in the keys to dot ("-" vs. ".") because dots in tag IDs are problematic and for the selectors, you should use "#process-payment-cardno" instead of "div[id=...]".

Can you change that? Afterwards, we will be happy to merge your PR :-)

**Comment by tenkraD** [comment]
If u dont use payment.cardno the label field will not be translated.

I think if you use - instead of . the language translation must be corrected

**Comment by aimeos** [comment]
Good point. After having a look into the HTML specs, dots are allowed in ID attributes. Only question left: Does `#process-payment.cardno` work or only `div[id="process-payment.cardno"]`?

**Comment by tenkraD** [comment]
No `#process-payment.cardno` dosen't work.
I tried it before cause it would be the easier selector to understand.

Just `div[id="process-payment.cardno"]` works cause of the point.

**Comment by aimeos** [comment]
OK, then we have to leave this as is. Can you change the type from `div` to `container`? Then we will merge your PR

**Comment by tenkraD** [comment]
I changed it, do i have to do a new pr?

**Comment by aimeos** [comment]
Thanks. Your PR has been automatically updated

**Comment by aimeos** [comment]
Your PR has been merged into 2018.10 too and a new release tagged

**Pull request merged**
